<script setup lang="ts">
import { computed, ref } from 'vue'
import { BarChart3, TrendingUp, ShoppingCart, Users, Package, IndianRupee, ArrowUpRight } from 'lucide-vue-next'
import { useShopStore } from '../stores/shopStore'
const store=useShopStore(); const range=ref('All time')
const orders=computed(()=>store.orders)
const revenue=computed(()=>orders.value.reduce((s,o)=>s+o.total,0))
const avgOrder=computed(()=>orders.value.length?revenue.value/orders.value.length:0)
const delivered=computed(()=>orders.value.filter(o=>o.status==='Delivered').length)
const conversionProxy=computed(()=>orders.value.length?((delivered.value/orders.value.length)*100):0)
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN')
const productSales=computed(()=>store.products.map(p=>({name:p.name,sales:p.sales,revenue:p.price*p.sales})).sort((a,b)=>b.revenue-a.revenue).slice(0,8))
const categoryStats=computed(()=>store.categories.map(c=>{const ps=store.products.filter(p=>p.categoryId===c.id);return {name:c.name,revenue:ps.reduce((s,p)=>s+p.price*p.sales,0),units:ps.reduce((s,p)=>s+p.sales,0)}}).sort((a,b)=>b.revenue-a.revenue)))
const paymentStats=computed(()=>['Paid','Pending','Failed','Refunded'].map(s=>({name:s,count:orders.value.filter(o=>o.paymentStatus===s).length})))
const statusStats=computed(()=>['Delivered','Shipped','Processing','Pending','Cancelled','Refunded'].map(s=>({name:s,count:orders.value.filter(o=>o.status===s).length})))
const maxRevenue=computed(()=>Math.max(...categoryStats.value.map(x=>x.revenue),1))
</script>
<template>
<section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-[1500px]">
<div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700"><BarChart3 :size="14"/> Business intelligence</div><h1 class="text-3xl font-extrabold text-slate-950">Analytics</h1><p class="mt-1 text-sm text-slate-500">Understand revenue, orders, customers and product performance.</p></div><select v-model="range" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm"><option>All time</option><option>Last 30 days</option><option>Last 90 days</option></select></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="stat"><IndianRupee/><span>Total revenue</span><strong>{{money(revenue)}}</strong><small>From {{orders.length}} orders</small></div><div class="stat"><ShoppingCart/><span>Average order value</span><strong>{{money(avgOrder)}}</strong><small>Revenue / order</small></div><div class="stat"><TrendingUp/><span>Delivered rate</span><strong>{{conversionProxy.toFixed(1)}}%</strong><small>{{delivered}} delivered orders</small></div><div class="stat"><Users/><span>Customers</span><strong>{{store.customers.length}}</strong><small>Across all segments</small></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="panel"><div class="flex items-center justify-between"><div><h2 class="title">Category revenue</h2><p class="sub">Revenue potential from product sales</p></div><Package class="text-orange-500"/></div><div class="mt-7 space-y-5"><div v-for="c in categoryStats" :key="c.name"><div class="mb-2 flex justify-between text-sm"><span class="font-semibold">{{c.name}}</span><span class="font-bold">{{money(c.revenue)}}</span></div><div class="h-2.5 rounded-full bg-orange-100"><div class="h-2.5 rounded-full bg-orange-400 transition-all" :style="{width:(c.revenue/maxRevenue*100)+'%'}"></div></div></div></div></div>
<div class="panel"><h2 class="title">Order status</h2><p class="sub">Current fulfillment distribution</p><div class="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><div v-for="s in statusStats" :key="s.name" class="rounded-xl bg-slate-50 p-4 transition hover:-translate-y-0.5 hover:bg-orange-50"><span class="text-xs text-slate-500">{{s.name}}</span><strong class="mt-1 block text-xl">{{s.count}}</strong></div></div></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="panel"><h2 class="title">Top products by revenue</h2><p class="sub">Highest estimated product contribution</p><div class="mt-5 space-y-3"><div v-for="(p,i) in productSales" :key="p.name" class="flex items-center gap-3 rounded-xl p-3 transition hover:bg-orange-50"><span class="grid h-8 w-8 place-items-center rounded-lg bg-orange-100 text-xs font-bold text-orange-700">{{i+1}}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{p.name}}</p><div class="mt-1 h-1.5 rounded-full bg-slate-100"><div class="h-1.5 rounded-full bg-orange-400" :style="{width:Math.min(100,(p.revenue/productSales[0].revenue)*100)+'%'}"></div></div></div><span class="text-sm font-bold">{{money(p.revenue)}}</span></div></div></div>
<div class="panel"><h2 class="title">Payment performance</h2><p class="sub">Payment status distribution</p><div class="mt-6 space-y-4"><div v-for="p in paymentStats" :key="p.name" class="flex items-center justify-between rounded-xl border border-slate-100 p-4"><div class="flex items-center gap-3"><span class="h-2.5 w-2.5 rounded-full bg-orange-400"></span><span class="font-medium">{{p.name}}</span></div><span class="rounded-full bg-orange-50 px-3 py-1 text-sm font-bold text-orange-700">{{p.count}}</span></div></div></div></div>
<div class="mt-6 panel"><div class="flex items-center justify-between"><div><h2 class="title">Business snapshot</h2><p class="sub">Quick metrics calculated from the current store data</p></div><ArrowUpRight class="text-orange-500"/></div><div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-xl bg-orange-50 p-4"><span class="text-xs text-orange-700">Products</span><strong class="mt-1 block text-xl">{{store.products.length}}</strong></div><div class="rounded-xl bg-orange-50 p-4"><span class="text-xs text-orange-700">Categories</span><strong class="mt-1 block text-xl">{{store.categories.length}}</strong></div><div class="rounded-xl bg-orange-50 p-4"><span class="text-xs text-orange-700">Low stock</span><strong class="mt-1 block text-xl">{{store.lowStockProducts.length}}</strong></div><div class="rounded-xl bg-orange-50 p-4"><span class="text-xs text-orange-700">Avg. customer spend</span><strong class="mt-1 block text-xl">{{money(store.customers.length?store.customers.reduce((s,c)=>s+c.totalSpent,0)/store.customers.length:0)}}</strong></div></div></div>
</div></section>
</template>
<style scoped>.stat,.panel{border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:1.25rem;transition:.25s}.stat:hover,.panel:hover{box-shadow:0 15px 35px -25px rgba(249,115,22,.35)}.stat svg{width:19px;color:#ea580c}.stat span{display:block;margin-top:.55rem;font-size:.75rem;color:#64748b}.stat strong{display:block;margin-top:.25rem;font-size:1.4rem;color:#0f172a}.stat small{display:block;margin-top:.2rem;font-size:.7rem;color:#94a3b8}.title{font-size:1rem;font-weight:700;color:#0f172a}.sub{margin-top:.2rem;font-size:.75rem;color:#94a3b8}</style>