<script setup lang="ts">
import { computed, ref } from 'vue'
import { FolderTree, Search, Plus, Pencil, Trash2, Package, X } from 'lucide-vue-next'
import { useShopStore } from '../stores/shopStore'
import type { Category } from '../types/ecommerce'
const store=useShopStore(); const search=ref(''); const modal=ref(false); const editing=ref<Category|null>(null); const error=ref(''); const form=ref({name:'',slug:''})
const rows=computed(()=>store.categories.filter(c=>[c.name,c.slug,c.id].some(v=>v.toLowerCase().includes(search.value.toLowerCase()))))
const count=(id:string)=>store.products.filter(p=>p.categoryId===id).length
const openCreate=()=>{editing.value=null;form.value={name:'',slug:''};error.value='';modal.value=true}
const openEdit=(c:Category)=>{editing.value=c;form.value={name:c.name,slug:c.slug};error.value='';modal.value=true}
const save=()=>{const name=form.value.name.trim(),slug=form.value.slug.trim().toLowerCase().replace(/\s+/g,'-');if(!name||!slug){error.value='Name and slug are required.';return}if(store.categories.some(c=>c.id!==editing.value?.id&&(c.name.toLowerCase()===name.toLowerCase()||c.slug===slug))){error.value='Category already exists.';return}if(editing.value)store.updateCategory(editing.value.id,{name,slug});else store.addCategory({id:'CAT-'+Date.now(),name,slug});modal.value=false}
const remove=(c:Category)=>{if(count(c.id)){error.value=c.name+' is used by '+count(c.id)+' product(s). Reassign products before deleting.';return}if(confirm('Delete '+c.name+'?'))store.deleteCategory(c.id)}
</script>
<template>
<section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-6xl">
<div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700"><FolderTree :size="14"/> Catalog management</div><h1 class="text-3xl font-extrabold text-slate-950">Categories</h1><p class="mt-1 text-sm text-slate-500">Organize products and keep your catalog structure clean.</p></div><button @click="openCreate" class="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-white"><Plus :size="17"/> Add category</button></div>
<div class="mb-5 grid gap-4 sm:grid-cols-3"><div class="stat"><FolderTree/><span>Total categories</span><strong>{{store.categories.length}}</strong></div><div class="stat"><Package/><span>Products assigned</span><strong>{{store.products.filter(p=>p.categoryId).length}}</strong></div><div class="stat"><Package/><span>Largest category</span><strong>{{Math.max(...store.categories.map(c=>count(c.id)),0)}}</strong><small>Products in one category</small></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="relative"><Search :size="17" class="absolute left-3 top-2.5 text-slate-400"/><input v-model="search" placeholder="Search category name, slug or ID..." class="w-full rounded-xl border border-slate-200 py-2.5 pl-9 text-sm outline-none focus:border-orange-400"/></div></div>
<div class="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="w-full text-left text-sm"><thead class="bg-orange-50/70 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Category</th><th class="px-5 py-3">Slug</th><th class="px-5 py-3">Products</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody><tr v-for="c in rows" :key="c.id" class="border-t border-slate-100 hover:bg-orange-50/40"><td class="px-5 py-4 font-semibold">{{c.name}}</td><td class="px-5 py-4 font-mono text-xs text-slate-500">/{{c.slug}}</td><td class="px-5 py-4 font-semibold">{{count(c.id)}}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><button @click="openEdit(c)" class="rounded-lg p-2 hover:bg-orange-50"><Pencil :size="16"/></button><button @click="remove(c)" class="rounded-lg p-2 hover:bg-red-50"><Trash2 :size="16"/></button></div></td></tr></tbody></table></div>
<p v-if="error" class="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">{{error}} <button @click="error=''" class="font-bold">×</button></p>
</div></section>
<div v-if="modal" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4" @click.self="modal=false"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div class="flex justify-between"><h2 class="text-xl font-bold">{{editing?'Edit':'Add'}} category</h2><button @click="modal=false"><X/></button></div><label class="mt-6 block text-sm font-medium">Name<input v-model="form.name" class="mt-1 w-full rounded-xl border p-3"/></label><label class="mt-4 block text-sm font-medium">Slug<input v-model="form.slug" class="mt-1 w-full rounded-xl border p-3"/></label><p v-if="error" class="mt-3 text-sm text-red-600">{{error}}</p><div class="mt-6 flex justify-end gap-2"><button @click="modal=false" class="rounded-xl border px-4 py-2">Cancel</button><button @click="save" class="rounded-xl bg-orange-500 px-4 py-2 font-semibold text-white">Save</button></div></div></div>
</template>
<style scoped>.stat{border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:1rem;transition:.25s}.stat:hover{transform:translateY(-2px);box-shadow:0 15px 35px -25px rgba(249,115,22,.35)}.stat svg{width:18px;color:#ea580c}.stat span{display:block;margin-top:.4rem;font-size:.75rem;color:#64748b}.stat strong{display:block;margin-top:.25rem;font-size:1.35rem}.stat small{display:block;margin-top:.2rem;font-size:.7rem;color:#94a3b8}</style>