<script setup lang="ts">
import { computed, ref } from 'vue'
import { Search, Users, MapPin, ChevronLeft, ChevronRight, X, ArrowUpRight } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { useShopStore } from '../stores/shopStore'
const store=useShopStore(); const router=useRouter()
const search=ref(''); const segment=ref('All'); const page=ref(1); const perPage=10
const filtered=computed(()=>[...store.customers].filter(c=>(!search.value||[c.name,c.email,c.id,c.city].some(v=>v.toLowerCase().includes(search.value.toLowerCase())))&&(segment.value==='All'||c.segment===segment.value)).sort((a,b)=>b.totalSpent-a.totalSpent))
const totalPages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/perPage))); const rows=computed(()=>filtered.value.slice((page.value-1)*perPage,page.value*perPage))
const money=(n:number)=>'₹'+n.toLocaleString('en-IN'); const date=(d:string)=>new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})
const changePage=(n:number)=>page.value=Math.min(totalPages.value,Math.max(1,n)); const reset=()=>{search.value='';segment.value='All';page.value=1}; const hasFilters=computed(()=>!!search.value||segment.value!=='All')
const segmentClass=(s:string)=>s==='VIP'?'bg-orange-100 text-orange-700':s==='Returning'?'bg-blue-50 text-blue-700':s==='New'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'
const totalSpent=computed(()=>store.customers.reduce((s,c)=>s+c.totalSpent,0)); const activeCustomers=computed(()=>store.customers.filter(c=>c.segment!=='Inactive').length)
</script>
<template><section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-[1500px]">
<div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700"><Users :size="14"/> Customer management</div><h1 class="text-3xl font-extrabold tracking-tight text-slate-950">Customers</h1><p class="mt-1 text-sm text-slate-500">Understand customer value, segments and purchase activity.</p></div><div class="rounded-2xl bg-orange-500 px-5 py-3 text-white shadow-lg shadow-orange-500/20"><p class="text-[11px] font-semibold text-orange-100">CUSTOMER LIFETIME VALUE</p><p class="mt-0.5 text-xl font-extrabold">{{money(totalSpent)}}</p></div></div>
<div class="mb-5 grid gap-4 sm:grid-cols-3"><div class="stat"><span>Total customers</span><strong>{{store.totalCustomers}}</strong><small>Registered profiles</small></div><div class="stat"><span>Active customers</span><strong>{{activeCustomers}}</strong><small>New + returning + VIP</small></div><div class="stat"><span>VIP customers</span><strong>{{store.customers.filter(c=>c.segment==='VIP').length}}</strong><small>High-value segment</small></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex flex-wrap gap-3"><div class="relative min-w-[260px] flex-1"><Search :size="17" class="absolute left-3 top-2.5 text-slate-400"/><input v-model="search" @input="page=1" placeholder="Search name, email, ID or city..." class="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"/></div><select v-model="segment" @change="page=1" class="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="All">All segments</option><option>VIP</option><option>Returning</option><option>New</option><option>Inactive</option></select><button v-if="hasFilters" @click="reset" class="flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-sm"><X :size="15"/> Clear</button></div></div>
<div class="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-left text-sm"><thead class="bg-orange-50/70 text-[11px] uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Location</th><th class="px-5 py-3">Orders</th><th class="px-5 py-3">Total spent</th><th class="px-5 py-3">Segment</th><th class="px-5 py-3">Joined</th><th></th></tr></thead><tbody><tr v-for="c in rows" :key="c.id" @click="router.push('/customers/'+c.id)" class="group cursor-pointer border-t border-slate-100 transition hover:bg-orange-50/40"><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-full bg-orange-50 font-bold text-orange-600">{{c.name.split(' ').map(n=>n[0]).join('').slice(0,2)}}</div><div><p class="font-bold text-slate-800 group-hover:text-orange-700">{{c.name}}</p><p class="text-xs text-slate-400">{{c.email}}</p></div></div></td><td class="px-5 py-4"><div class="flex items-center gap-1.5 text-slate-600"><MapPin :size="14" class="text-slate-400"/>{{c.city}}, {{c.state}}</div></td><td class="px-5 py-4 font-medium">{{c.ordersCount}}</td><td class="px-5 py-4 font-bold">{{money(c.totalSpent)}}</td><td class="px-5 py-4"><span :class="segmentClass(c.segment)" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{c.segment}}</span></td><td class="px-5 py-4 text-slate-500">{{date(c.joinedAt)}}</td><td class="px-5 py-4"><ArrowUpRight :size="16" class="text-slate-300 transition group-hover:text-orange-500"/></td></tr><tr v-if="!rows.length"><td colspan="7" class="py-16 text-center text-slate-500">No customers match your filters.</td></tr></tbody></table></div>
<div class="flex items-center justify-between border-t px-5 py-4"><span class="text-xs text-slate-400">Showing {{filtered.length?((page-1)*perPage+1):0}}–{{Math.min(page*perPage,filtered.length)}} of {{filtered.length}}</span><div class="flex items-center gap-1"><button @click="changePage(page-1)" :disabled="page===1" class="grid h-8 w-8 place-items-center rounded-lg hover:bg-orange-50 disabled:opacity-30"><ChevronLeft :size="16"/></button><button v-for="n in totalPages" :key="n" @click="changePage(n)" :class="['h-8 min-w-8 rounded-lg px-2 text-sm font-medium',page===n?'bg-orange-500 text-white':'hover:bg-orange-50']">{{n}}</button><button @click="changePage(page+1)" :disabled="page===totalPages" class="grid h-8 w-8 place-items-center rounded-lg hover:bg-orange-50 disabled:opacity-30"><ChevronRight :size="16"/></button></div></div></div>
</div></section></template>
<style scoped>.stat{border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:1rem;transition:all .25s}.stat:hover{transform:translateY(-2px);box-shadow:0 15px 35px -25px rgba(249,115,22,.35)}.stat span{display:block;font-size:.75rem;color:#64748b}.stat strong{display:block;margin-top:.3rem;font-size:1.4rem;color:#0f172a}.stat small{display:block;margin-top:.2rem;font-size:.72rem;color:#94a3b8}</style>