<script setup lang="ts">
import { computed } from 'vue'
import { ArrowLeft, Mail, MapPin, CalendarDays, ShoppingBag, WalletCards, UserRound, Package } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { useShopStore } from '../stores/shopStore'
const route=useRoute(); const router=useRouter(); const store=useShopStore()
const customer=computed(()=>store.customers.find(c=>c.id===route.params.id))
const orders=computed(()=>customer.value?store.orders.filter(o=>o.customerId===customer.value!.id).sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt)):[])
const money=(n:number)=>'₹'+n.toLocaleString('en-IN')
const date=(d:string)=>new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})
const initials=computed(()=>customer.value?.name.split(' ').map(n=>n[0]).join('').slice(0,2)??'')
const segmentClass=(s:string)=>s==='VIP'?'bg-orange-100 text-orange-700':s==='Returning'?'bg-blue-50 text-blue-700':s==='New'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'
</script>
<template>
<section v-if="customer" class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] px-5 py-6 sm:px-6 lg:px-8"><div class="mx-auto max-w-6xl">
<button @click="router.push('/customers')" class="mb-6 flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-orange-700"><ArrowLeft :size="17"/> Back to customers</button>
<div class="rounded-3xl border border-orange-100 bg-white p-6 shadow-xl shadow-orange-100/40 sm:p-8"><div class="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-4"><div class="grid h-16 w-16 place-items-center rounded-2xl bg-orange-50 text-lg font-extrabold text-orange-600">{{initials}}</div><div><div class="flex flex-wrap items-center gap-2"><span :class="segmentClass(customer.segment)" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{customer.segment}}</span><span class="text-xs text-slate-400">{{customer.id}}</span></div><h1 class="mt-2 text-2xl font-bold text-slate-950">{{customer.name}}</h1><p class="mt-1 text-sm text-slate-500">{{customer.email}}</p></div></div><a :href="'mailto:'+customer.email" class="flex w-fit items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-orange-500/20 hover:bg-orange-600"><Mail :size="16"/> Email customer</a></div>
<div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="kpi"><ShoppingBag :size="18"/><span>Orders</span><strong>{{customer.ordersCount}}</strong></div><div class="kpi"><WalletCards :size="18"/><span>Total spent</span><strong>{{money(customer.totalSpent)}}</strong></div><div class="kpi"><MapPin :size="18"/><span>Location</span><strong class="!text-base">{{customer.city}}</strong></div><div class="kpi"><CalendarDays :size="18"/><span>Customer since</span><strong class="!text-base">{{date(customer.joinedAt)}}</strong></div></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-6 lg:col-span-2"><div class="flex items-center justify-between"><h2 class="font-semibold">Order history</h2><span class="text-xs text-slate-400">{{orders.length}} linked orders</span></div><div v-if="orders.length" class="mt-5 space-y-3"><button v-for="o in orders" :key="o.id" @click="router.push('/orders/'+o.id)" class="flex w-full items-center justify-between rounded-xl border border-slate-100 p-4 text-left transition hover:border-orange-200 hover:bg-orange-50/40"><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-600"><Package :size="17"/></div><div><p class="font-semibold text-slate-800">{{o.id}}</p><p class="text-xs text-slate-400">{{date(o.createdAt)}} · {{o.status}}</p></div></div><span class="font-bold text-slate-800">{{money(o.total)}}</span></button></div><div v-else class="py-14 text-center text-sm text-slate-500"><UserRound :size="32" class="mx-auto mb-3 text-slate-300"/>No orders are linked to this customer yet.</div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Profile</h2><div class="mt-5 space-y-4"><div><p class="text-xs text-slate-400">Email</p><p class="mt-1 text-sm font-medium">{{customer.email}}</p></div><div><p class="text-xs text-slate-400">Location</p><p class="mt-1 text-sm font-medium">{{customer.city}}, {{customer.state}}, {{customer.country}}</p></div><div><p class="text-xs text-slate-400">Average order value</p><p class="mt-1 text-sm font-medium">{{money(customer.ordersCount?customer.totalSpent/customer.ordersCount:0)}}</p></div><div><p class="text-xs text-slate-400">Customer ID</p><p class="mt-1 text-sm font-medium">{{customer.id}}</p></div></div></div></div>
</div></section>
<section v-else class="grid min-h-[calc(100vh-4rem)] place-items-center bg-[#f7f7fc]"><div class="text-center"><UserRound :size="40" class="mx-auto text-slate-300"/><h1 class="mt-4 text-xl font-bold">Customer not found</h1><button @click="router.push('/customers')" class="mt-4 rounded-xl bg-orange-500 px-4 py-2 text-sm font-semibold text-white">Back to customers</button></div></section>
</template>
<style scoped>.kpi{border-radius:1rem;background:#fff7ed;padding:1rem;color:#ea580c}.kpi span{display:block;margin-top:.35rem;font-size:.72rem;color:#64748b}.kpi strong{display:block;margin-top:.2rem;font-size:1.25rem;color:#0f172a}</style>