<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowUpRight, AlertTriangle, DollarSign, Package, ShoppingCart, Sparkles, TrendingUp, Users, Clock3, Activity, ExternalLink } from 'lucide-vue-next'
import { useShopStore } from '../stores/shopStore'
const store=useShopStore(); const period=ref('Last 30 days')
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN')
const stats=computed(()=>[
 {label:'Gross revenue',value:money(store.totalRevenue),change:'+12.8%',icon:DollarSign,detail:'vs previous period'},
 {label:'Orders',value:store.totalOrders.toLocaleString('en-IN'),change:'+8.4%',icon:ShoppingCart,detail:'all channels'},
 {label:'Customers',value:store.totalCustomers.toLocaleString('en-IN'),change:'+5.7%',icon:Users,detail:'registered accounts'},
 {label:'Inventory risk',value:store.lowStockProducts.length.toString(),change:'Needs attention',icon:Package,detail:'below reorder level',warn:true}
])
const recentOrders=computed(()=>[...store.orders].sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt)).slice(0,7))
const customerName=(id:string)=>store.customers.find(c=>c.id===id)?.name??'Unknown'
const topProducts=computed(()=>[...store.products].sort((a,b)=>b.sales-a.sales).slice(0,5))
const monthlyRevenue=[42000,51000,47000,62000,58000,71000,68000,79000,74000,86000,82000,94000]
const monthLabels=['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep']
const orderMix=computed(()=>['Delivered','Processing','Shipped','Pending'].map(label=>({label,value:store.orders.filter(o=>o.status===label).length})))
const maxOrders=computed(()=>Math.max(...orderMix.value.map(x=>x.value),1))
const statusClass=(s:string)=>s==='Delivered'?'bg-emerald-50 text-emerald-700':s==='Cancelled'||s==='Refunded'?'bg-rose-50 text-rose-700':s==='Shipped'?'bg-blue-50 text-blue-700':'bg-orange-50 text-orange-700'
</script>
<template>
<section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-[1500px]">
<div class="mb-7 flex flex-wrap items-end justify-between gap-5"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full border border-orange-100 bg-white px-3 py-1 text-xs font-bold text-orange-700 shadow-sm"><Sparkles :size="13"/> Live commerce workspace</div><h1 class="text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">Good afternoon, Admin.</h1><p class="mt-2 text-sm text-slate-500">Here’s what’s happening across your store today.</p></div><div class="flex items-center gap-3"><select v-model="period" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold shadow-sm outline-none focus:border-orange-400"><option>Today</option><option>Last 7 days</option><option>Last 30 days</option><option>This year</option></select><RouterLink to="/reports" class="hidden rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-orange-500/20 transition hover:-translate-y-0.5 sm:block">View reports</RouterLink></div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="stat in stats" :key="stat.label" class="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-orange-500/10"><div class="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-orange-50 transition duration-500 group-hover:scale-150"/><div class="relative flex items-start justify-between"><div :class="stat.warn?'bg-amber-50 text-amber-600':'bg-orange-50 text-orange-600'" class="grid h-10 w-10 place-items-center rounded-xl"><component :is="stat.icon" :size="19"/></div><ArrowUpRight :size="17" class="text-slate-300 transition group-hover:text-orange-500"/></div><p class="mt-5 text-xs font-medium text-slate-500">{{stat.label}}</p><p class="mt-1 text-2xl font-black tracking-tight">{{stat.value}}</p><div class="mt-2 flex items-center gap-2 text-[11px]"><span :class="stat.warn?'text-amber-600':'text-emerald-600'" class="font-bold">{{stat.change}}</span><span class="text-slate-400">{{stat.detail}}</span></div></div></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3">
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><div class="flex items-start justify-between"><div><h2 class="font-bold">Revenue overview</h2><p class="mt-1 text-xs text-slate-400">Monthly performance · hover for exact values</p></div><div class="rounded-xl bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">+12.8% YoY</div></div><div class="mt-8 flex h-60 items-end gap-2 sm:gap-3"><div v-for="(value,i) in monthlyRevenue" :key="monthLabels[i]" class="group relative flex h-full flex-1 items-end"><div :style="{height:(value/100000*100)+'%'}" class="w-full min-h-[10px] rounded-t-lg bg-orange-200 transition duration-500 group-hover:bg-orange-500 group-hover:-translate-y-1"/><span class="absolute -top-7 left-1/2 -translate-x-1/2 rounded-lg bg-slate-950 px-2 py-1 text-[10px] font-bold text-white opacity-0 shadow-xl transition group-hover:opacity-100">₹{{value.toLocaleString('en-IN')}}</span></div></div><div class="mt-3 flex justify-between text-[10px] font-semibold text-slate-400"><span v-for="m in monthLabels" :key="m">{{m}}</span></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-bold">Order health</h2><p class="mt-1 text-xs text-slate-400">Current fulfillment mix</p></div><Activity :size="19" class="text-orange-500"/></div><div class="mt-7 space-y-5"><div v-for="item in orderMix" :key="item.label"><div class="mb-2 flex justify-between text-xs"><span class="font-semibold text-slate-600">{{item.label}}</span><span class="font-black">{{item.value}}</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-orange-400 transition-all duration-700" :style="{width:(item.value/maxOrders*100)+'%'}"/></div></div></div><RouterLink to="/orders" class="mt-7 flex items-center justify-center gap-2 rounded-xl border border-slate-200 py-2.5 text-xs font-bold text-slate-600 transition hover:border-orange-200 hover:bg-orange-50 hover:text-orange-700">Open order center <ExternalLink :size="14"/></RouterLink></div>
</div>
<div class="mt-6 grid gap-6 lg:grid-cols-5">
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3"><div class="flex items-center justify-between"><div><h2 class="font-bold">Recent orders</h2><p class="mt-1 text-xs text-slate-400">Latest customer transactions</p></div><RouterLink to="/orders" class="text-xs font-bold text-orange-600 hover:underline">View all</RouterLink></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead class="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="pb-3">Order</th><th class="pb-3">Customer</th><th class="pb-3">Amount</th><th class="pb-3">Status</th></tr></thead><tbody><tr v-for="r in recentOrders" :key="r.id" @click="$router.push('/orders/'+r.id)" class="cursor-pointer border-b border-slate-50 transition hover:bg-orange-50/40"><td class="py-4 font-bold">{{r.id}}</td><td class="py-4">{{customerName(r.customerId)}}</td><td class="py-4 font-bold">{{money(r.total)}}</td><td class="py-4"><span :class="statusClass(r.status)" class="rounded-full px-2.5 py-1 text-[11px] font-semibold">{{r.status}}</span></td></tr></tbody></table></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold">Top products</h2><p class="mt-1 text-xs text-slate-400">Units sold</p></div><RouterLink to="/products" class="text-xs font-bold text-orange-600">Catalog</RouterLink></div><div class="mt-5 space-y-4"><div v-for="(p,i) in topProducts" :key="p.id" class="flex items-center gap-3"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-orange-50 text-xs font-black text-orange-700">{{i+1}}</span><div class="min-w-0 flex-1"><div class="flex justify-between gap-3"><p class="truncate text-xs font-bold">{{p.name}}</p><span class="text-[11px] font-bold text-slate-500">{{p.sales.toLocaleString('en-IN')}}</span></div><div class="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-orange-400" :style="{width:Math.min(100,Math.max(8,p.sales/Math.max(1,topProducts[0]?.sales||1)*100))+'%'}"/></div></div></div></div></div>
</div>
<div class="mt-6 grid gap-6 lg:grid-cols-3">
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center gap-3"><div class="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-600"><AlertTriangle :size="17"/></div><div><h2 class="font-bold">Inventory alerts</h2><p class="text-xs text-slate-400">{{store.lowStockProducts.length}} products need attention</p></div></div><div class="mt-5 space-y-2.5"><RouterLink v-for="p in store.lowStockProducts.slice(0,4)" :key="p.id" to="/inventory" class="flex items-center justify-between rounded-xl border border-slate-100 p-3 transition hover:border-amber-200 hover:bg-amber-50/40"><span class="min-w-0"><strong class="block truncate text-xs">{{p.name}}</strong><small class="text-[10px] text-slate-400">{{p.stock}} left · reorder {{p.reorderLevel}}</small></span><ArrowUpRight :size="14" class="text-slate-300"/></RouterLink></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div class="flex items-center justify-between"><div><h2 class="font-bold">Recent activity</h2><p class="mt-1 text-xs text-slate-400">Latest workspace events</p></div><Clock3 :size="18" class="text-slate-300"/></div><div class="mt-4 space-y-3"><div v-for="a in store.activities.slice(0,5)" :key="a.id" class="flex gap-3 rounded-xl p-2 transition hover:bg-orange-50/50"><div class="mt-1 h-2 w-2 shrink-0 rounded-full bg-orange-400"/><div class="min-w-0"><p class="text-xs font-bold">{{a.action}}</p><p class="truncate text-[11px] text-slate-500">{{a.detail}}</p></div><span class="ml-auto whitespace-nowrap text-[10px] text-slate-400">{{new Date(a.createdAt).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}}</span></div></div></div>
</div>
</div></section>
</template>