<script setup lang="ts">
import { computed, ref } from 'vue'
import { Search, Package, AlertTriangle, Boxes, IndianRupee, ArrowUpRight, ChevronLeft, ChevronRight, X, Plus, Minus } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { useShopStore } from '../stores/shopStore'
const store=useShopStore(); const router=useRouter()
const search=ref(''); const filter=ref('All'); const page=ref(1); const perPage=10
const selected=ref<any>(null); const adjustment=ref(0); const note=ref('')
const rows=computed(()=>store.products.filter(p=>{
 const matchesSearch=!search.value||[p.name,p.sku,p.id].some(v=>v.toLowerCase().includes(search.value.toLowerCase()))
 const matchesFilter=filter.value==='All'||(filter.value==='Low'&&p.stock>0&&p.stock<=p.reorderLevel)||(filter.value==='Out'&&p.stock===0)
 return matchesSearch&&matchesFilter
}))
const totalPages=computed(()=>Math.max(1,Math.ceil(rows.value.length/perPage)))
const paginated=computed(()=>rows.value.slice((page.value-1)*perPage,page.value*perPage))
const low=computed(()=>store.products.filter(p=>p.stock>0&&p.stock<=p.reorderLevel).length)
const out=computed(()=>store.products.filter(p=>p.stock===0).length)
const stockValue=computed(()=>store.products.reduce((s,p)=>s+p.stock*p.costPrice,0))
const totalUnits=computed(()=>store.products.reduce((s,p)=>s+p.stock,0))
const money=(n:number)=>'₹'+n.toLocaleString('en-IN')
const reset=()=>{search.value='';filter.value='All';page.value=1}
const hasFilters=computed(()=>!!search.value||filter.value!=='All')
const stockLabel=(p:any)=>p.stock===0?'Out of stock':p.stock<=p.reorderLevel?'Low stock':'Healthy'
const stockClass=(p:any)=>p.stock===0?'bg-red-50 text-red-700':p.stock<=p.reorderLevel?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'
const openAdjustment=(p:any)=>{selected.value=p;adjustment.value=0;note.value=''}
const closeAdjustment=()=>{selected.value=null}
const saveAdjustment=()=>{if(!selected.value||!adjustment.value)return;if(store.adjustStock(selected.value.id,adjustment.value,note.value||'Manual stock adjustment'))closeAdjustment()}
</script>
<template>
<section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-[1500px]">
<div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700"><Boxes :size="14"/> Inventory management</div><h1 class="text-3xl font-extrabold text-slate-950">Inventory</h1><p class="mt-1 text-sm text-slate-500">Monitor stock levels, reorder thresholds and inventory value.</p></div></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="stat"><Package/><span>Total units</span><strong>{{totalUnits.toLocaleString('en-IN')}}</strong></div><div class="stat"><AlertTriangle/><span>Low stock</span><strong>{{low}}</strong></div><div class="stat"><AlertTriangle/><span>Out of stock</span><strong>{{out}}</strong></div><div class="stat"><IndianRupee/><span>Stock value</span><strong>{{money(stockValue)}}</strong></div></div>
<div class="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex flex-wrap gap-3"><div class="relative min-w-[260px] flex-1"><Search :size="17" class="absolute left-3 top-2.5 text-slate-400"/><input v-model="search" @input="page=1" placeholder="Search product, SKU or ID..." class="w-full rounded-xl border border-slate-200 py-2.5 pl-9 text-sm outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"/></div><select v-model="filter" @change="page=1" class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>All</option><option>Low</option><option>Out</option></select><button v-if="hasFilters" @click="reset" class="flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-sm"><X :size="15"/>Clear</button></div></div>
<div class="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-left text-sm"><thead class="bg-orange-50/70 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Product</th><th class="px-5 py-3">Category</th><th class="px-5 py-3">Stock</th><th class="px-5 py-3">Reorder level</th><th class="px-5 py-3">Stock value</th><th class="px-5 py-3">Health</th><th class="px-5 py-3">Action</th></tr></thead><tbody><tr v-for="p in paginated" :key="p.id" class="group border-t transition hover:bg-orange-50/40"><td @click="router.push('/products/'+p.id)" class="cursor-pointer px-5 py-4"><div class="flex items-center gap-3"><div class="grid h-9 w-9 place-items-center rounded-lg bg-orange-50 text-orange-600"><Package :size="16"/></div><div><p class="font-semibold group-hover:text-orange-700">{{p.name}}</p><p class="text-xs text-slate-400">{{p.sku}}</p></div></div></td><td class="px-5 py-4">{{store.categories.find(c=>c.id===p.categoryId)?.name}}</td><td class="px-5 py-4 font-bold">{{p.stock}}</td><td class="px-5 py-4 text-slate-500">{{p.reorderLevel}}</td><td class="px-5 py-4 font-semibold">{{money(p.stock*p.costPrice)}}</td><td class="px-5 py-4"><span :class="stockClass(p)" class="rounded-full px-2.5 py-1 text-xs font-semibold">{{stockLabel(p)}}</span></td><td class="px-5 py-4"><button @click="openAdjustment(p)" class="inline-flex items-center gap-1.5 rounded-lg border border-orange-200 px-3 py-1.5 text-xs font-semibold text-orange-700 hover:bg-orange-50"><ArrowUpRight :size="14"/>Adjust</button></td></tr><tr v-if="!paginated.length"><td colspan="7" class="py-16 text-center text-slate-500">No inventory records match your filters.</td></tr></tbody></table></div>
<div class="flex items-center justify-between border-t px-5 py-4"><span class="text-xs text-slate-400">Showing {{rows.length?((page-1)*perPage+1):0}}–{{Math.min(page*perPage,rows.length)}} of {{rows.length}}</span><div class="flex gap-1"><button @click="page=Math.max(1,page-1)" :disabled="page===1" class="grid h-8 w-8 place-items-center rounded-lg hover:bg-orange-50 disabled:opacity-30"><ChevronLeft :size="16"/></button><button v-for="n in totalPages" :key="n" @click="page=n" :class="['h-8 min-w-8 rounded-lg px-2 text-sm',page===n?'bg-orange-500 text-white':'hover:bg-orange-50']">{{n}}</button><button @click="page=Math.min(totalPages,page+1)" :disabled="page===totalPages" class="grid h-8 w-8 place-items-center rounded-lg hover:bg-orange-50 disabled:opacity-30"><ChevronRight :size="16"/></button></div></div></div>
</div></section>
<div v-if="selected" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4" @click.self="closeAdjustment"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-orange-600">Stock adjustment</p><h2 class="mt-1 text-xl font-bold text-slate-950">{{selected.name}}</h2><p class="mt-1 text-sm text-slate-500">Current stock: {{selected.stock}}</p></div><button @click="closeAdjustment" class="rounded-lg p-2 hover:bg-slate-100"><X :size="18"/></button></div><div class="mt-6 grid grid-cols-2 gap-3"><button @click="adjustment=Math.max(1,adjustment)" :class="['rounded-xl border p-3 text-sm font-semibold',adjustment>=0?'border-orange-300 bg-orange-50 text-orange-700':'border-slate-200']"><Plus :size="16" class="mx-auto mb-1"/>Restock</button><button @click="adjustment=Math.min(-1,adjustment)" :class="['rounded-xl border p-3 text-sm font-semibold',adjustment<0?'border-orange-300 bg-orange-50 text-orange-700':'border-slate-200']"><Minus :size="16" class="mx-auto mb-1"/>Remove stock</button></div><label class="mt-5 block text-sm font-medium text-slate-700">Quantity<input v-model.number="adjustment" type="number" :min="adjustment<0?-selected.stock:1" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-orange-400"/></label><label class="mt-4 block text-sm font-medium text-slate-700">Note<input v-model="note" placeholder="e.g. Supplier delivery / damaged item" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-orange-400"/></label><div class="mt-6 flex justify-end gap-2"><button @click="closeAdjustment" class="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button @click="saveAdjustment" :disabled="!adjustment||adjustment<0&&Math.abs(adjustment)>selected.stock" class="rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Save adjustment</button></div></div></div>
</template>
<style scoped>.stat{border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:1.1rem;transition:.25s}.stat:hover{transform:translateY(-2px);box-shadow:0 15px 35px -25px rgba(249,115,22,.35)}.stat svg{width:18px;color:#ea580c}.stat span{display:block;margin-top:.6rem;font-size:.75rem;color:#64748b}.stat strong{display:block;margin-top:.25rem;font-size:1.35rem;color:#0f172a}</style>