<script setup lang="ts">
import { computed, ref } from 'vue'
import { FileText, Download, ShoppingCart, IndianRupee, Package, Users } from 'lucide-vue-next'
import { useShopStore } from '../stores/shopStore'
const store=useShopStore()
const reportType=ref('Sales Report'), period=ref('All time'), search=ref('')
const days=computed(()=>period.value==='Last 30 days'?30:period.value==='Last 90 days'?90:null)
const orders=computed(()=>store.orders.filter(o=>!days.value||Date.now()-new Date(o.createdAt).getTime()<=days.value*86400000))
const revenue=computed(()=>orders.value.reduce((s,o)=>s+o.total,0))
const units=computed(()=>orders.value.reduce((s,o)=>s+o.items.reduce((n,i)=>n+i.quantity,0),0))
const money=(n:number)=>'₹'+Math.round(n).toLocaleString('en-IN')
const rows=computed(()=>{const q=search.value.toLowerCase(); if(reportType.value==='Customers') return store.customers.filter(c=>!q||[c.name,c.email,c.id].some(v=>v.toLowerCase().includes(q))); if(reportType.value==='Inventory') return store.products.filter(p=>!q||[p.name,p.sku,p.id].some(v=>v.toLowerCase().includes(q))); return orders.value.filter(o=>!q||o.id.toLowerCase().includes(q))})
const headers=computed(()=>reportType.value==='Customers'?['Customer','Email','Segment','Orders','Total spent']:reportType.value==='Inventory'?['Product','SKU','Stock','Reorder','Stock value']:['Order','Date','Status','Payment','Total'])
const exportCsv=()=>{let data:any[]=[];if(reportType.value==='Customers')data=rows.value.map((c:any)=>[c.name,c.email,c.segment,c.ordersCount,money(c.totalSpent)]);else if(reportType.value==='Inventory')data=rows.value.map((p:any)=>[p.name,p.sku,p.stock,p.reorderLevel,money(p.stock*p.costPrice)]);else data=rows.value.map((o:any)=>[o.id,new Date(o.createdAt).toLocaleDateString('en-IN'),o.status,o.paymentStatus,money(o.total)]);const csv=[headers.value,...data].map(r=>r.map((v:any)=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=reportType.value.replace(/ /g,'_')+'_Report.csv';a.click()}
</script>
<template>
<section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-[1500px]">
<div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700"><FileText :size="14"/> Business reporting</div><h1 class="text-3xl font-extrabold text-slate-950">Reports</h1><p class="mt-1 text-sm text-slate-500">Generate operational reports from your current store data.</p></div><button @click="exportCsv" class="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-white"><Download :size="17"/> Export CSV</button></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="stat"><ShoppingCart/><span>Orders</span><strong>{{orders.length}}</strong></div><div class="stat"><IndianRupee/><span>Revenue</span><strong>{{money(revenue)}}</strong></div><div class="stat"><Package/><span>Units sold</span><strong>{{units.toLocaleString('en-IN')}}</strong></div><div class="stat"><Users/><span>Customers</span><strong>{{store.customers.length}}</strong></div></div>
<div class="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 md:grid-cols-3"><label class="text-xs font-semibold text-slate-500">Report type<select v-model="reportType" class="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>Sales Report</option><option>Customers</option><option>Inventory</option></select></label><label class="text-xs font-semibold text-slate-500">Period<select v-model="period" class="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option>All time</option><option>Last 30 days</option><option>Last 90 days</option></select></label><label class="text-xs font-semibold text-slate-500">Search<input v-model="search" placeholder="Search records..." class="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label></div></div>
<div class="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-orange-50/70 text-xs uppercase text-slate-500"><tr><th v-for="h in headers" :key="h" class="px-5 py-3">{{h}}</th></tr></thead><tbody><tr v-for="r in rows" :key="r.id" class="border-t border-slate-100 hover:bg-orange-50/40"><template v-if="reportType==='Sales Report'"><td class="px-5 py-4">{{r.id}}</td><td class="px-5 py-4">{{new Date(r.createdAt).toLocaleDateString('en-IN')}}</td><td class="px-5 py-4">{{r.status}}</td><td class="px-5 py-4">{{r.paymentStatus}}</td><td class="px-5 py-4 font-semibold">{{money(r.total)}}</td></template><template v-else-if="reportType==='Customers'"><td class="px-5 py-4">{{r.name}}</td><td class="px-5 py-4">{{r.email}}</td><td class="px-5 py-4">{{r.segment}}</td><td class="px-5 py-4">{{r.ordersCount}}</td><td class="px-5 py-4 font-semibold">{{money(r.totalSpent)}}</td></template><template v-else><td class="px-5 py-4">{{r.name}}</td><td class="px-5 py-4">{{r.sku}}</td><td class="px-5 py-4">{{r.stock}}</td><td class="px-5 py-4">{{r.reorderLevel}}</td><td class="px-5 py-4 font-semibold">{{money(r.stock*r.costPrice)}}</td></template></tr><tr v-if="!rows.length"><td :colspan="headers.length" class="py-16 text-center text-slate-500">No report records found.</td></tr></tbody></table></div>
</div></section>
</template>
<style scoped>.stat{border:1px solid #e2e8f0;border-radius:1rem;background:#fff;padding:1.1rem;transition:.25s}.stat:hover{transform:translateY(-2px);box-shadow:0 15px 35px -25px rgba(249,115,22,.35)}.stat svg{width:18px;color:#ea580c}.stat span{display:block;margin-top:.6rem;font-size:.75rem;color:#64748b}.stat strong{display:block;margin-top:.25rem;font-size:1.35rem;color:#0f172a}</style>