<script setup lang="ts">
import { ref } from 'vue'
import { Settings2, ShieldCheck, Bell, Palette, Database, CheckCircle2 } from 'lucide-vue-next'
const saved=ref(false)
const form=ref({storeName:'ShopPulse Store',currency:'INR (₹)',timezone:'Asia/Kolkata',emailAlerts:true,lowStockAlerts:true,weeklyReport:true})
const save=()=>{saved.value=true;setTimeout(()=>saved.value=false,1800)}
</script>
<template>
<section class="min-h-[calc(100vh-4rem)] bg-[#f7f7fc] p-5 sm:p-6 lg:p-8"><div class="mx-auto max-w-5xl">
<div class="mb-7"><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700"><Settings2 :size="14"/> Workspace configuration</div><h1 class="text-3xl font-black text-slate-950">Settings</h1><p class="mt-1 text-sm text-slate-500">Configure store preferences, notifications and workspace behavior.</p></div>
<div class="grid gap-6 lg:grid-cols-[1fr_300px]">
<div class="space-y-6">
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-600"><Database :size="18"/></div><div><h2 class="font-bold">Store preferences</h2><p class="text-xs text-slate-400">Core workspace configuration</p></div></div><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="label">Store name<input v-model="form.storeName" class="field"/></label><label class="label">Currency<select v-model="form.currency" class="field"><option>INR (₹)</option><option>USD ($)</option><option>EUR (€)</option></select></label><label class="label sm:col-span-2">Timezone<select v-model="form.timezone" class="field"><option>Asia/Kolkata</option><option>UTC</option><option>Asia/Dubai</option></select></label></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-600"><Bell :size="18"/></div><div><h2 class="font-bold">Notifications</h2><p class="text-xs text-slate-400">Control operational alerts</p></div></div><div class="mt-5 divide-y divide-slate-100"><label v-for="item in [['emailAlerts','Email order alerts','Receive important order updates'],['lowStockAlerts','Low-stock alerts','Notify when products reach reorder level'],['weeklyReport','Weekly business report','Receive a weekly performance summary']]" :key="item[0]" class="flex cursor-pointer items-center justify-between gap-4 py-4"><span><b class="block text-sm">{{item[1]}}</b><small class="text-xs text-slate-400">{{item[2]}}</small></span><input v-model="form[item[0]]" type="checkbox" class="h-5 w-5 accent-orange-500"/></label></div></div>
<div class="flex items-center justify-end gap-3"><span v-if="saved" class="flex items-center gap-1.5 text-xs font-semibold text-emerald-600"><CheckCircle2 :size="15"/> Settings saved</span><button @click="save" class="rounded-xl bg-orange-500 px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-orange-500/20 hover:bg-orange-600">Save changes</button></div>
</div>
<div class="space-y-5"><div class="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm"><ShieldCheck :size="21" class="text-orange-400"/><h2 class="mt-4 font-bold">Admin workspace</h2><p class="mt-2 text-xs leading-5 text-slate-400">This demo workspace uses role-ready architecture so authentication and permissions can be connected to a real backend later.</p><div class="mt-5 rounded-xl bg-white/5 p-3 text-xs"><span class="text-slate-400">Current role</span><b class="mt-1 block">Administrator</b></div></div><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center gap-3"><Palette :size="18" class="text-orange-500"/><h2 class="font-bold">Appearance</h2></div><div class="mt-5 rounded-xl border border-orange-100 bg-orange-50 p-4"><p class="text-xs font-bold text-orange-800">Warm Orange</p><p class="mt-1 text-xs text-orange-700/70">Clean light theme optimized for operational dashboards.</p></div></div></div>
</div></div></section>
</template>
<style scoped>.label{display:block;font-size:.75rem;font-weight:600;color:#475569}.field{display:block;width:100%;margin-top:.45rem;border:1px solid #e2e8f0;border-radius:.75rem;padding:.65rem .8rem;font-size:.875rem;font-weight:400;outline:none;background:#fff}.field:focus{border-color:#fb923c;box-shadow:0 0 0 3px rgba(249,115,22,.12)}</style>